# Generated by Django 4.2.5 on 2023-10-10 02:16

# Third-Party Libraries
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_num", models.IntegerField(db_column="StreetNum")),
                (
                    "street_name",
                    models.CharField(db_column="StreetName", max_length=100),
                ),
                ("box_area", models.CharField(db_column="BoxArea", max_length=10)),
                (
                    "apt_num",
                    models.CharField(
                        blank=True, db_column="AptNum", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Address",
                "ordering": ["box_area", "street_name"],
            },
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="Name",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "Committee",
            },
        ),
        migrations.CreateModel(
            name="CourseCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_column="Code",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=50)),
            ],
            options={
                "db_table": "CourseCode",
            },
        ),
        migrations.CreateModel(
            name="HourType",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="Name",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "min_hours",
                    models.IntegerField(blank=True, db_column="MinHours", null=True),
                ),
            ],
            options={
                "db_table": "HourType",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "badge_num",
                    models.IntegerField(
                        db_column="BadgeNum", primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(db_column="FirstName", max_length=50)),
                ("last_name", models.CharField(db_column="LastName", max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Member",
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "abbr",
                    models.CharField(
                        db_column="Abbr",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_officer", models.IntegerField(db_column="IsOfficer")),
                ("name", models.CharField(db_column="Name", max_length=100)),
            ],
            options={
                "db_table": "Rank",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "call_sign",
                    models.CharField(
                        db_column="CallSign",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unit_type", models.CharField(db_column="UnitType", max_length=10)),
                ("max_crew", models.IntegerField(db_column="MaxCrew")),
            ],
            options={
                "db_table": "Unit",
            },
        ),
        migrations.CreateModel(
            name="TrainingReport",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("training_date", models.DateTimeField(db_column="TrainingDate")),
                ("sub_date", models.DateTimeField(db_column="SubDate")),
                ("certified", models.BooleanField(db_column="Certified")),
                ("num_hours", models.FloatField(db_column="numHours")),
                (
                    "description",
                    models.CharField(db_column="Description", max_length=50),
                ),
                (
                    "course_code",
                    models.ForeignKey(
                        db_column="CourseCode",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.coursecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Report",
                "db_table": "TrainingReport",
            },
        ),
        migrations.CreateModel(
            name="StandBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(db_column="StartTime")),
                ("end_time", models.DateTimeField(db_column="EndTime")),
                (
                    "losap_valid",
                    models.BooleanField(db_column="LOSAPValid", default=False),
                ),
                (
                    "badge_num",
                    models.ForeignKey(
                        db_column="BadgeNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standby",
                        to="api.member",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        db_column="Type",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.hourtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stand By",
                "db_table": "StandBy",
            },
        ),
        migrations.CreateModel(
            name="SleepIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(db_column="Date")),
                (
                    "badge_num",
                    models.ForeignKey(
                        db_column="BadgeNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleepin",
                        to="api.member",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        db_column="Type",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.hourtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sleep In",
                "db_table": "SleepIn",
            },
        ),
        migrations.AddField(
            model_name="member",
            name="rank",
            field=models.ForeignKey(
                db_column="Rank",
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.rank",
            ),
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "incident_num",
                    models.IntegerField(
                        db_column="IncidentNum", primary_key=True, serialize=False
                    ),
                ),
                (
                    "incidentType",
                    models.CharField(
                        blank=True, db_column="IncidentType", max_length=10, null=True
                    ),
                ),
                (
                    "officer",
                    models.IntegerField(blank=True, db_column="Officer", null=True),
                ),
                ("dispatch_time", models.DateTimeField(db_column="DispatchTime")),
                (
                    "cleared_time",
                    models.DateTimeField(
                        blank=True, db_column="ClearedTime", null=True
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        blank=True, db_column="CreatedTime", null=True
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        blank=True, db_column="UpdatedTime", null=True
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        db_column="Address",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.address",
                    ),
                ),
            ],
            options={
                "db_table": "Incident",
            },
        ),
        migrations.CreateModel(
            name="CollateralDuty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(db_column="StartTime")),
                ("end_time", models.DateTimeField(db_column="EndTime")),
                (
                    "description",
                    models.CharField(db_column="Description", max_length=120),
                ),
                (
                    "losap_valid",
                    models.BooleanField(db_column="LOSAPValid", default=False),
                ),
                (
                    "badge_num",
                    models.ForeignKey(
                        db_column="BadgeNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collateralduty",
                        to="api.member",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        db_column="Committee",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.committee",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        db_column="Type",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.hourtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collateral Duty",
                "db_table": "CollateralDuty",
            },
        ),
        migrations.CreateModel(
            name="UnitResponse",
            fields=[
                (
                    "call_sign",
                    models.OneToOneField(
                        db_column="CallSign",
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="api.unit",
                    ),
                ),
                ("dispatch_time", models.DateTimeField(db_column="DispatchTime")),
                (
                    "cleared_time",
                    models.DateTimeField(
                        blank=True, db_column="ClearedTime", null=True
                    ),
                ),
                (
                    "incident_num",
                    models.ForeignKey(
                        db_column="IncidentNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit Response",
                "db_table": "UnitResponse",
                "ordering": ["incident_num", "call_sign"],
            },
        ),
        migrations.CreateModel(
            name="MemberTrainingReport",
            fields=[
                (
                    "badge_num",
                    models.OneToOneField(
                        db_column="BadgeNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.member",
                    ),
                ),
                (
                    "training_report",
                    models.ForeignKey(
                        db_column="TrainingReport",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.trainingreport",
                    ),
                ),
            ],
            options={
                "db_table": "MemberTrainingReport",
                "ordering": ["training_report", "badge_num"],
            },
        ),
        migrations.CreateModel(
            name="MemberResponse",
            fields=[
                (
                    "badge_num",
                    models.OneToOneField(
                        db_column="BadgeNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.member",
                    ),
                ),
                (
                    "rank_at_time",
                    models.CharField(
                        blank=True, db_column="RankAtTime", max_length=10, null=True
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="Unit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberresponse_unit_set",
                        to="api.unitresponse",
                    ),
                ),
            ],
            options={
                "db_table": "MemberResponse",
                "ordering": ["unit__incident_num", "unit__call_sign", "badge_num"],
            },
        ),
    ]
