version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ..:/workspace
    command: sleep infinity
    environment:
      DJANGO_SETTINGS_MODULE: lva2.settings.devcontainer
      # SECURITY WARNING: keep the secret key used in production secret!
      SECRET_KEY: ')njwhhlatzp1=%s0q33w*4g4f5pyjhil&gzqgh$c_ira5(2nye'
      DATABASE_USER: "admin"
      DATABASE_PWD: "OvfcLosap"

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../db_data:/var/lib/mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: OvfcLosap
      MYSQL_ROOT_PASSWORD: OvfcLosap
      MYSQL_DATABASE: LVA2